version: "3"
services:
    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - ${APP_PORT:-80}:80
            - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
        tty: true
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - mysql
            - app

    app:
        build: .
        restart: unless-stopped
        working_dir: /var/www/
        tty: true
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - mysql


    mysql:
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "0.0.0.0"
        tty: true
        healthcheck:
            test: ["CMD-SHELL", 'mysqladmin ping -u=$$DB_USERNAME -p=$$DB_PASSWORD']
            interval: 30s
            timeout: 10s
            retries: 10
        volumes:
            - ./docker/mysql/mysqldata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
            - ./docker/mysql/mysql-files:/var/lib/mysql-files/

volumes:
    mysqldata:
        driver: local
